language: go

go:
  - 1.9

# Don't email me the results of the test runs.
notifications:
  email: false


install:
  - go get github.com/kardianos/govendor
  - govendor sync
  - govendor list

script:
  - govendor vet +local
  - govendor test +local